version: '2'
services:
  app:
    build: .
    command: bundle exec foreman start
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: development
      MYSQL_ROOT_PASSWORD: 'root'
      DATABASE_URL: 'mysql2://root:root@db:3306'
    depends_on:
      - db
    volumes:
      - ./:/myapp
      - bundle:/bundle
      - node_modules:/myapp/client/node_modules
    links:
      - db
  nginx:
    build: containers/nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
    volumes:
      - ./containers_data/nginx:/var/log/nginx
    links:
      - app
  db:
    image: mysql:5.6.32
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - ./containers_data/db:/var/lib/mysql
volumes:
  bundle:
  node_modules:
